{% set name = "curviriver" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/curviriver-{{ version }}.tar.gz
  sha256: 8693a816d65b18c79efc843bbaafaf4bcf7c50e1e2b713e813fe27ffa075cc4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - cytoolz
    - geopandas >=0.12
    - networkx >=2.5
    - numpy >=1.21
    - pandas >=1
    - pyproj >=2.2
    - scikit-learn >=1.3
    - scipy
    - shapely >=2

test:
  imports:
    - curviriver
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://curviriver.readthedocs.io
  summary: Generate curvilinear mesh from river outline polygons
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
